services:
  - type: web
    name: ai-data-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MISTRAL_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false 